### ISSUE TITLE
Runtime Error Uncaught (in promise): false

### ISSUE THREAD

**Issue by crossiono** [javebratt/ionic-angularfire2-email-auth#1]
Error: Uncaught (in promise): false
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:35509:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at HTMLElement.invoke (http://localhost:8100/build/polyfills.js:3:10876)

Error
Close
Runtime Error
Uncaught (in promise): false
Stack
Error: Uncaught (in promise): false
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:35509:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at HTMLElement.invoke (http://localhost:8100/build/polyfills.js:3:10876)

any ideas.

**Comment by javebratt** [comment]
What are you trying to do when you get the error?

**Comment by crossiono** [comment]
It opens fine.  when i sign up everything goes to firebase, but then it gets this error.  It also did it when i tried to log in (without signing up first) it came back with this error.

**Comment by javebratt** [comment]
Hey @crossiono I noticed the promise is breaking because in `app.component.ts` I'm telling the app to change pages depending on auth state, and when we're logging in or out we're repeating that.

Going to use this coming week to update everything to RC5 and AngularFire beta 7

**Comment by chandanch** [comment]
Uncaught (in promise): false
    at g (polyfills.js:3)
    at l (polyfills.js:3)
    at l (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4136)
    at t.invokeTask (polyfills.js:3)
    at n.runTask (polyfills.js:3)
    at a (polyfills.js:3)
